version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "${PORT:-8080}:${CONTAINER_PORT:-8080}"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    command: gradle bootRun --no-daemon --x test
    networks:
      - my-network

networks:
  my-network:
    external: true
